name: Merge Script

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'  # 每6小时一次
  workflow_dispatch:  # 触发手动事件

permissions:
  contents: write  # 允许GITHUB_TOKEN进行写操作

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main  # 确保 checkout 的是 main 分支
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run merged proxies script
        run: python merged_proxies.py

      - name: Check for changes
        id: check_changes
        run: |
          git status --porcelain > changes.txt  # 保存文件更改状态
          if [[ -s changes.txt ]]; then
            echo "true" > changes_detected.txt
          else
            echo "false" > changes_detected.txt
        continue-on-error: false

      - name: Commit and push changes
        if: ${{ steps.check_changes.outputs.changes_detected == 'true' }}
        run: |
          git config core.ignorecase false
          git config user.email "actions@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Updated at $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main  # 确保推送到 main 分支
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
