name: Merge Script

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'  # 每6小时一次
  workflow_dispatch:  # 触发手动事件

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run merged proxies script
        run: |
          python merged_proxies.py
          cat ./sub/merged_proxies.yaml

      - name: Check file content and Git status
        run: |
          echo "Files in sub directory:"
          ls -la ./sub
          echo "Content of merged_proxies.yaml:"
          cat ./sub/merged_proxies.yaml
          echo "Git status:"
          git status

      - name: Check for changes
        id: check_changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Action"
          git add -A
          git diff --cached --quiet || echo "Changes detected" > changes_detected.txt
          if [ -s changes_detected.txt ]; then
            echo "Changes detected."
            echo "::set-output name=changes_detected::true"
          else
            echo "No changes detected."
            echo "::set-output name=changes_detected::false"
          fi

      - name: List files in the repository
        run: ls -la

      - name: Check git diff
        run: git diff

      - name: Show git diff
        run: git diff --cached

      - name: Show git status
        run: git status

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git commit -m "Update triggered at $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
